<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\KtxSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="16x16_colors_Compressonator.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="16x16_colors_PVRTexTool.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="testimage_SIGNED_R11_EAC.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="ktx_specs.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="etc2-rgba8.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="smiling_etc_64x64_Compressonator.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="smiling_ATC_RGBA_Explicit.ktx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="format_pvrtc1_4bpp_unorm.ktx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>